### List all users
GET http://localhost:8080/api/user

### Create a new user
POST http://localhost:8080/api/user
content-type: application/json

{
  "username": "sample",
  "password": "password",
  "firstName": "Steven",
  "lastName": "King"
}

### Update an existing user
POST http://localhost:8080/api/user
content-type: application/json

{
  "username": "sample",
  "password": "secret",
  "firstName": "Steven",
  "lastName": "King"
}

### Delete a user
DELETE http://localhost:8080/api/user
content-type: application/json

{
  "username": "sample"
}

### User login
POST http://localhost:3000/glacier/login
content-type: application/x-www-form-urlencoded

username=jmyyang&password=test

### List all scheduled batch jobs
GET http://localhost:3000/glacier/api/schedule